### ISSUE TITLE
plot3 and plot4 have unattractive proportions. Help!!!!

### ISSUE THREAD

**Issue by wuxiangning** [zktuong/ktplots#117] opened 2024-10-22 04:45 UTC
plot_cpdb3(cell_type1='Neu_01_SPP1',cell_type2='Neu_05_APOA2',
           scdata=sce_obj,
           celltype_key="celltype",
           means=means,
           pvals=pvals,
           deconvoluted=decon2,# new options from here on specific to plot_cpdb3
           keep_significant_only=TRUE,
           standard_scale=TRUE,
           remove_self=TRUE
)
![{09EAE2B6-5AEC-4242-B3F3-8342140754A1}](https://github.com/user-attachments/assets/9f3b5039-2544-45b9-ab6a-851487fd9e03)
Hello, I would like to know why the chord diagrams I created using your standard code for plot3 and plot4 have very strange and unattractive proportions. The same issue occurs when I use your test data. Is there any way to adjust this? I urgently need help.
Thanks!

**Comment by zktuong** [comment] 2024-10-22 09:56
hi, it's probably due to your plotting window size. if you are using jupyer:
https://stackoverflow.com/questions/42729049/how-to-change-the-size-of-r-plots-in-jupyter

otherwise, you should be able to drag your window size and make them bigger?

**Comment by wuxiangning** [comment] 2024-10-22 16:13
Well.I didn't run it in Jupyter; I ran this line of code in R, and even when I maximized it on my 27-inch computer, it still looked small and distorted. This is the case regardless of whether I use my data or the demo data you provided.

**Comment by wuxiangning** [comment] 2024-10-22 16:14
I don't know how to modify the code to adjust the proportions in R; they seem to be abnormal.

**Comment by zktuong** [comment] 2024-10-22 22:56
i'm not exactly sure what's going wrong here as i don't include any code that sets the dimensions of the plot and i can't see if `circlize` has defaults too. have you tried closing and reopening a new R session incase there's some remnant undesired plotting setting set in your workspace? Don't load `~/.Rdata` as well, just in case .

**Comment by wuxiangning** [comment] 2024-10-23 02:36
But how can I import my SingleExperiment and plot it without loading ~/.Rdata? Perhaps using an RDS file could solve this issue?
Thanks!

**Comment by zktuong** [comment] 2024-10-23 04:36
I would advise that you should **never** ever save and load anything in `~/.RData`. It's a really bad practice, especially when dealing with multiple projects at the same time, but is unfortunately part of R's "feature". Definitely just save/read with RDS.

**Comment by wuxiangning** [comment] 2024-10-23 05:42
seu<-readRDS(file = "F:/Rdata/Selected_data/cluster0909.rds")
library(SingleCellExperiment)
library(sceasy)
sce_obj <- as.SingleCellExperiment(seu)
means <- read.delim("E:/statistical_analysis_means_10_17_2024_112330.txt", check.names = FALSE)
pvals <- read.delim("E:/statistical_analysis_pvalues_10_17_2024_112330.txt",  check.names = FALSE)
deconvoluted2<-read.delim('E:/statistical_analysis_deconvoluted_10_17_2024_112330.txt',check.names=FALSE)
However, I initially used RDS to read the data, and the issue still occurred. I don't think it's related to the Rdata file.

**Comment by zktuong** [comment] 2024-10-23 08:18
so i can't really reproduce this issue base on the files you have sent me:

```R
library(Seurat)
library(SingleCellExperiment)
library(ktplots)

setwd("~/Downloads/ktplots_test")
seu <- readRDS("test_cellphoneDB.rds")
sce <- as.SingleCellExperiment(seu)

means <- read.delim("statistical_analysis_means_10_23_2024_104822.txt", check.names=F)
pvals <- read.delim("statistical_analysis_pvalues_10_23_2024_104822.txt", check.names=F)
decon <- read.delim("statistical_analysis_deconvoluted_10_23_2024_104822.txt", check.names=F)

colnames(means) <- gsub("纬未 T cells", "γδ T cells", colnames(means))
colnames(pvals) <- gsub("纬未 T cells", "γδ T cells", colnames(pvals))
colnames(decon) <- gsub("纬未 T cells", "γδ T cells", colnames(decon))

dev.new(width=10, height=5)
plot_cpdb(
	scdata=sce,
	cell_type1="Tumor cells",
	cell_type2="T cells",
	celltype_key="labels",
	genes="TNFSF14",
	means=means,
	pvals=pvals
	)
#dev.off()

dev.new(width=6, height=6)
plot_cpdb3(
	scdata=sce,
	cell_type1="Tumor cells",
	cell_type2="T cells",
	celltype_key="labels",
	genes="TNFSF14",
	means=means,
	pvals=pvals,
	deconvoluted=decon,# new options from here on specific to plot_cpdb3
	keep_significant_only=TRUE,
	standard_scale=TRUE,
	remove_self=TRUE
	)
#dev.off()

dev.new(width=6, height=6)
plot_cpdb4(
	scdata=sce,
	cell_type1="Tumor cells",
	cell_type2="T cells",
	celltype_key="labels",
	interaction="TNFSF14-TNFRSF14",
	means=means,
	pvals=pvals,
	deconvoluted=decon,# new options from here on specific to plot_cpdb3
	keep_significant_only=TRUE,
	standard_scale=TRUE,
	remove_self=TRUE
	)
#dev.off()
```

This are my plots:

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/28347f84-29a5-44ed-8c13-8fd8f0a169dc">

<img width="710" alt="image" src="https://github.com/user-attachments/assets/9c3e68fc-2485-4f1e-ae63-81a452a002f0">

<img width="723" alt="image" src="https://github.com/user-attachments/assets/9b8dbb04-ee93-4212-8719-41aacaf2119d">

**Comment by wuxiangning** [comment] 2024-10-23 11:15
Thank you! I successfully ran the code you shared. The issue earlier might have been that I didn't set `dev.new(width=6, height=6)`. I also wanted to ask if I can adjust the spacing and thickness of each label, as well as set different colors for the different cell types? 
Many thanks!

**Comment by wuxiangning** [comment] 2024-10-23 14:33
When I used plot_cpdb4 to examine the VEGF interaction between two specific cell groups, I encountered this error. Is the warning due to the absence of any interactions? However, it was still able to generate a chord diagram. I'm not sure if this result is correct, or if this warning can be ignored.
警告信息:
1: In `[<-.factor`(`*tmp*`, iseq, value = c(0, 0, 0, 0, 0, 0, 0, 0,  :
  因子水平有错误，产生了NA
2: Since you have set `group`, you should better set `grid.col` as a named vector where sector names are the vector names (should contain all sectors).

**Comment by zktuong** [comment] 2024-10-23 23:17
yup that's just a warning that you can ignore.

> I also wanted to ask if I can adjust the spacing and thickness of each label, as well as set different colors for the different cell types?
there's some minimal options 
https://zktuong.github.io/ktplots/reference/plot_cpdb3.html
https://zktuong.github.io/ktplots/reference/plot_cpdb4.html

**Comment by wuxiangning** [comment] 2024-10-24 04:29
Sure!
Thanks!

**Closed** 2024-10-28 06:34 UTC
